import = ["/home/tudor/.config/alacritty/themes/themes/hyper.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 2

# [font.bold]
# family = "JetBrainsMono Nerd Font"
# style = "Bold"
#
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# style = "Italic"
#
# [font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# style = "Bold Italic"


[window]
opacity = 1
