format = '$all'
right_format = '$time'

[character]
success_symbol = '[\$](bold green)'
error_symbol   = '[\$](bold red)'
vimcmd_symbol  = '[V](bold blue)'

[time]
disabled = false
format = '[$time]($style)'
style = 'bold black'
use_12hr = false
