local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>f', builtin.find_files, { desc = "find [f]iles" })
vim.keymap.set('n', '<leader>b', builtin.buffers, { desc = "find [b]uffers" })
vim.keymap.set('n', '<leader>sg', builtin.git_files, { desc = "[s]earch [g]it files" })
vim.keymap.set('n', '<leader>sh', builtin.help_tags, { desc = "[s]earch [h]elp tags" })
vim.keymap.set('n', '<leader>sc', builtin.colorscheme, { desc = "[s]earch [c]olorscheme" })
vim.keymap.set('n', '<leader>sk', builtin.keymaps, { desc = "[s]earch [k]eymaps" })
